const rates = {
  AF: {
    alpha3: "AFG",
    currencyCode: "AFN",
    countryName: "Afghanistan",
    currencyName: "Afghani",
    minorUnit: 2.0,
    currency_numeric_code: 971.0,
    rate: 20.1702155046,
    alpha2: "AF",
  },
  AL: {
    alpha3: "ALB",
    currencyCode: "ALL",
    countryName: "Albania",
    currencyName: "Lek",
    minorUnit: 2.0,
    currency_numeric_code: 8.0,
    rate: 55.1868688901,
    alpha2: "AL",
  },
  DZ: {
    alpha3: "DZA",
    currencyCode: "DZD",
    countryName: "Algeria",
    currencyName: "Algerian Dinar",
    minorUnit: 2.0,
    currency_numeric_code: 12.0,
    rate: 38.4164405089,
    alpha2: "DZ",
  },
  AO: {
    alpha3: "AGO",
    currencyCode: "AOA",
    countryName: "Angola",
    currencyName: "Kwanza",
    minorUnit: 2.0,
    currency_numeric_code: 973.0,
    rate: 132.3337711122,
    alpha2: "AO",
  },
  AG: {
    alpha3: "ATG",
    currencyCode: "XCD",
    countryName: "Antigua and Barbuda",
    currencyName: "East Caribbean Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 951.0,
    rate: 2.1878726729,
    alpha2: "AG",
  },
  AM: {
    alpha3: "ARM",
    currencyCode: "AMD",
    countryName: "Armenia",
    currencyName: "Armenian Dram",
    minorUnit: 2.0,
    currency_numeric_code: 51.0,
    rate: 197.0825228161,
    alpha2: "AM",
  },
  AW: {
    alpha3: "ABW",
    currencyCode: "AWG",
    countryName: "Aruba",
    currencyName: "Aruban Florin",
    minorUnit: 2.0,
    currency_numeric_code: 533.0,
    rate: 1.5208655971,
    alpha2: "AW",
  },
  AU: {
    alpha3: "AUS",
    currencyCode: "AUD",
    countryName: "Australia",
    currencyName: "Australian Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 36.0,
    rate: 1.603619,
    alpha2: "AU",
  },
  AT: {
    alpha3: "AUT",
    currencyCode: "EUR",
    countryName: "Austria",
    currencyName: "Euro",
    minorUnit: 2.0,
    currency_numeric_code: 978.0,
    rate: 0.853177,
    alpha2: "AT",
  },
  AZ: {
    alpha3: "AZE",
    currencyCode: "AZN",
    countryName: "Azerbaijan",
    currencyName: "Azerbaijanian Manat",
    minorUnit: 2.0,
    currency_numeric_code: 944.0,
    rate: 0.351318842,
    alpha2: "AZ",
  },
  BS: {
    alpha3: "BHS",
    currencyCode: "BSD",
    countryName: "Bahamas",
    currencyName: "Bahamian Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 44.0,
    rate: 1.1374821406,
    alpha2: "BS",
  },
  BH: {
    alpha3: "BHR",
    currencyCode: "BHD",
    countryName: "Bahrain",
    currencyName: "Bahraini Dinar",
    minorUnit: 3.0,
    currency_numeric_code: 48.0,
    rate: 0.2302700683,
    alpha2: "BH",
  },
  BD: {
    alpha3: "BGD",
    currencyCode: "BDT",
    countryName: "Bangladesh",
    currencyName: "Taka",
    minorUnit: 2.0,
    currency_numeric_code: 50.0,
    rate: 31.8887924346,
    alpha2: "BD",
  },
  BB: {
    alpha3: "BRB",
    currencyCode: "BBD",
    countryName: "Barbados",
    currencyName: "Barbados Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 52.0,
    rate: 2.4570529075,
    alpha2: "BB",
  },
  BY: {
    alpha3: "BLR",
    currencyCode: "BYR",
    countryName: "Belarus",
    currencyName: "Belarussian Ruble",
    minorUnit: 0.0,
    currency_numeric_code: 974.0,
    rate: 0.4852097744,
    alpha2: "BY",
  },
  BE: {
    alpha3: "BEL",
    currencyCode: "EUR",
    countryName: "Belgium",
    currencyName: "Euro",
    minorUnit: 2.0,
    currency_numeric_code: 978.0,
    rate: 0.877384,
    alpha2: "BE",
  },
  BZ: {
    alpha3: "BLZ",
    currencyCode: "BZD",
    countryName: "Belize",
    currencyName: "Belize Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 84.0,
    rate: 1.139435477,
    alpha2: "BZ",
  },
  BJ: {
    alpha3: "BEN",
    currencyCode: "XOF",
    countryName: "Benin",
    currencyName: "CFA Franc BCEAO",
    minorUnit: 0.0,
    currency_numeric_code: 952.0,
    rate: 223.375045112,
    alpha2: "BJ",
  },
  BT: {
    alpha3: "BTN",
    currencyCode: "INR",
    countryName: "Bhutan",
    currencyName: "Indian Rupee",
    minorUnit: 2.0,
    currency_numeric_code: 356.0,
    rate: 22.2754877358,
    alpha2: "BT",
  },
  BO: {
    alpha3: "BOL",
    currencyCode: "BOB",
    countryName: "Bolivia, Plurinational State of",
    currencyName: "Boliviano",
    minorUnit: 2.0,
    currency_numeric_code: 68.0,
    rate: 3.4350888384,
    alpha2: "BO",
  },
  BA: {
    alpha3: "BIH",
    currencyCode: "BAM",
    countryName: "Bosnia and Herzegovina",
    currencyName: "Convertible Mark",
    minorUnit: 2.0,
    currency_numeric_code: 977.0,
    rate: 0.8056885384,
    alpha2: "BA",
  },
  BW: {
    alpha3: "BWA",
    currencyCode: "BWP",
    countryName: "Botswana",
    currencyName: "Pula",
    minorUnit: 2.0,
    currency_numeric_code: 72.0,
    rate: 5.288207465,
    alpha2: "BW",
  },
  BR: {
    alpha3: "BRA",
    currencyCode: "BRL",
    countryName: "Brazil",
    currencyName: "Brazilian Real",
    minorUnit: 2.0,
    currency_numeric_code: 986.0,
    rate: 2.1938119957,
    alpha2: "BR",
  },
  BN: {
    alpha3: "BRN",
    currencyCode: "BND",
    countryName: "Brunei Darussalam",
    currencyName: "Brunei Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 96.0,
    rate: 0.7951463652,
    alpha2: "BN",
  },
  BG: {
    alpha3: "BGR",
    currencyCode: "BGN",
    countryName: "Bulgaria",
    currencyName: "Bulgarian Lev",
    minorUnit: 2.0,
    currency_numeric_code: 975.0,
    rate: 0.7513456974,
    alpha2: "BG",
  },
  BF: {
    alpha3: "BFA",
    currencyCode: "XOF",
    countryName: "Burkina Faso",
    currencyName: "CFA Franc BCEAO",
    minorUnit: 0.0,
    currency_numeric_code: 952.0,
    rate: 218.3650883053,
    alpha2: "BF",
  },
  BI: {
    alpha3: "BDI",
    currencyCode: "BIF",
    countryName: "Burundi",
    currencyName: "Burundi Franc",
    minorUnit: 0.0,
    currency_numeric_code: 108.0,
    rate: 676.5799823889,
    alpha2: "BI",
  },
  KH: {
    alpha3: "KHM",
    currencyCode: "KHR",
    countryName: "Cambodia",
    currencyName: "Riel",
    minorUnit: 2.0,
    currency_numeric_code: 116.0,
    rate: 1642.9227845505,
    alpha2: "KH",
  },
  CM: {
    alpha3: "CMR",
    currencyCode: "XAF",
    countryName: "Cameroon",
    currencyName: "CFA Franc BEAC",
    minorUnit: 0.0,
    currency_numeric_code: 950.0,
    rate: 239.2607617377,
    alpha2: "CM",
  },
  CA: {
    alpha3: "CAN",
    currencyCode: "CAD",
    countryName: "Canada",
    currencyName: "Canadian Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 124.0,
    rate: 1.355435,
    alpha2: "CA",
  },
  CV: {
    alpha3: "CPV",
    currencyCode: "CVE",
    countryName: "Cape Verde",
    currencyName: "Cabo Verde Escudo",
    minorUnit: 2.0,
    currency_numeric_code: 132.0,
    rate: 45.6997838129,
    alpha2: "CV",
  },
  KY: {
    alpha3: "CYM",
    currencyCode: "KYD",
    countryName: "Cayman Islands",
    currencyName: "Cayman Islands Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 136.0,
    rate: 1.0814145819,
    alpha2: "KY",
  },
  CL: {
    alpha3: "CHL",
    currencyCode: "CLP",
    countryName: "Chile",
    currencyName: "Chilean Peso",
    minorUnit: 0.0,
    currency_numeric_code: 152.0,
    rate: 455.085486,
    alpha2: "CL",
  },
  CN: {
    alpha3: "CHN",
    currencyCode: "CNY",
    countryName: "China",
    currencyName: "Yuan Renminbi",
    minorUnit: 2.0,
    currency_numeric_code: 156.0,
    rate: 3.851058131,
    alpha2: "CN",
  },
  CO: {
    alpha3: "COL",
    currencyCode: "COP",
    countryName: "Colombia",
    currencyName: "Colombian Peso",
    minorUnit: 2.0,
    currency_numeric_code: 170.0,
    rate: 1371.5419569536,
    alpha2: "CO",
  },
  CR: {
    alpha3: "CRI",
    currencyCode: "CRC",
    countryName: "Costa Rica",
    currencyName: "Costa Rican Colon",
    minorUnit: 2.0,
    currency_numeric_code: 188.0,
    rate: 373.2379659126,
    alpha2: "CR",
  },
  HR: {
    alpha3: "HRV",
    currencyCode: "HRK",
    countryName: "Croatia",
    currencyName: "Croatian Kuna",
    minorUnit: 2.0,
    currency_numeric_code: 191.0,
    rate: 4.0006034517,
    alpha2: "HR",
  },
  CY: {
    alpha3: "CYP",
    currencyCode: "EUR",
    countryName: "Cyprus",
    currencyName: "Euro",
    minorUnit: 2.0,
    currency_numeric_code: 978.0,
    rate: 0.7063193467,
    alpha2: "CY",
  },
  CZ: {
    alpha3: "CZE",
    currencyCode: "CZK",
    countryName: "Czech Republic",
    currencyName: "Czech Koruna",
    minorUnit: 2.0,
    currency_numeric_code: 203.0,
    rate: 14.282408,
    alpha2: "CZ",
  },
  CI: {
    alpha3: "CIV",
    currencyCode: "XOF",
    countryName: "C\u00f4te d'Ivoire",
    currencyName: "CFA Franc BCEAO",
    minorUnit: 0.0,
    currency_numeric_code: 952.0,
    rate: 235.137132327,
    alpha2: "CI",
  },
  DK: {
    alpha3: "DNK",
    currencyCode: "DKK",
    countryName: "Denmark",
    currencyName: "Danish Krone",
    minorUnit: 2.0,
    currency_numeric_code: 208.0,
    rate: 8.424346,
    alpha2: "DK",
  },
  DJ: {
    alpha3: "DJI",
    currencyCode: "DJF",
    countryName: "Djibouti",
    currencyName: "Djibouti Franc",
    minorUnit: 0.0,
    currency_numeric_code: 262.0,
    rate: 104.3149252917,
    alpha2: "DJ",
  },
  DM: {
    alpha3: "DMA",
    currencyCode: "XCD",
    countryName: "Dominica",
    currencyName: "East Caribbean Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 951.0,
    rate: 1.9692871645,
    alpha2: "DM",
  },
  DO: {
    alpha3: "DOM",
    currencyCode: "DOP",
    countryName: "Dominican Republic",
    currencyName: "Dominican Peso",
    minorUnit: 2.0,
    currency_numeric_code: 214.0,
    rate: 22.3008349213,
    alpha2: "DO",
  },
  EC: {
    alpha3: "ECU",
    currencyCode: "USD",
    countryName: "Ecuador",
    currencyName: "US Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 840.0,
    rate: 0.6066452676,
    alpha2: "EC",
  },
  EG: {
    alpha3: "EGY",
    currencyCode: "EGP",
    countryName: "Egypt",
    currencyName: "Egyptian Pound",
    minorUnit: 2.0,
    currency_numeric_code: 818.0,
    rate: 2.7400945047,
    alpha2: "EG",
  },
  SV: {
    alpha3: "SLV",
    currencyCode: "USD",
    countryName: "El Salvador",
    currencyName: "US Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 840.0,
    rate: 0.5150291506,
    alpha2: "SV",
  },
  GQ: {
    alpha3: "GNQ",
    currencyCode: "XAF",
    countryName: "Equatorial Guinea",
    currencyName: "CFA Franc BEAC",
    minorUnit: 0.0,
    currency_numeric_code: 950.0,
    rate: 345.6828508603,
    alpha2: "GQ",
  },
  EE: {
    alpha3: "EST",
    currencyCode: "EUR",
    countryName: "Estonia",
    currencyName: "Euro",
    minorUnit: 2.0,
    currency_numeric_code: 978.0,
    rate: 0.605856,
    alpha2: "EE",
  },
  ET: {
    alpha3: "ETH",
    currencyCode: "ETB",
    countryName: "Ethiopia",
    currencyName: "Ethiopian Birr",
    minorUnit: 2.0,
    currency_numeric_code: 230.0,
    rate: 8.5805989033,
    alpha2: "ET",
  },
  FJ: {
    alpha3: "FJI",
    currencyCode: "FJD",
    countryName: "Fiji",
    currencyName: "Fiji Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 242.0,
    rate: 1.2843955634,
    alpha2: "FJ",
  },
  FI: {
    alpha3: "FIN",
    currencyCode: "EUR",
    countryName: "Finland",
    currencyName: "Euro",
    minorUnit: 2.0,
    currency_numeric_code: 978.0,
    rate: 0.97406,
    alpha2: "FI",
  },
  FR: {
    alpha3: "FRA",
    currencyCode: "EUR",
    countryName: "France",
    currencyName: "Euro",
    minorUnit: 2.0,
    currency_numeric_code: 978.0,
    rate: 0.868215,
    alpha2: "FR",
  },
  GA: {
    alpha3: "GAB",
    currencyCode: "XAF",
    countryName: "Gabon",
    currencyName: "CFA Franc BEAC",
    minorUnit: 0.0,
    currency_numeric_code: 950.0,
    rate: 370.0046069354,
    alpha2: "GA",
  },
  GM: {
    alpha3: "GMB",
    currencyCode: "GMD",
    countryName: "Gambia",
    currencyName: "Dalasi",
    minorUnit: 2.0,
    currency_numeric_code: 270.0,
    rate: 13.5665625708,
    alpha2: "GM",
  },
  GE: {
    alpha3: "GEO",
    currencyCode: "GEL",
    countryName: "Georgia",
    currencyName: "Lari",
    minorUnit: 2.0,
    currency_numeric_code: 981.0,
    rate: 0.8513489436,
    alpha2: "GE",
  },
  DE: {
    alpha3: "DEU",
    currencyCode: "EUR",
    countryName: "Germany",
    currencyName: "Euro",
    minorUnit: 2.0,
    currency_numeric_code: 978.0,
    rate: 0.83106,
    alpha2: "DE",
  },
  GH: {
    alpha3: "GHA",
    currencyCode: "GHS",
    countryName: "Ghana",
    currencyName: "Ghana Cedi",
    minorUnit: 2.0,
    currency_numeric_code: 936.0,
    rate: 1.430092428,
    alpha2: "GH",
  },
  GR: {
    alpha3: "GRC",
    currencyCode: "EUR",
    countryName: "Greece",
    currencyName: "Euro",
    minorUnit: 2.0,
    currency_numeric_code: 978.0,
    rate: 0.67636,
    alpha2: "GR",
  },
  GD: {
    alpha3: "GRD",
    currencyCode: "XCD",
    countryName: "Grenada",
    currencyName: "East Caribbean Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 951.0,
    rate: 2.0094594204,
    alpha2: "GD",
  },
  GT: {
    alpha3: "GTM",
    currencyCode: "GTQ",
    countryName: "Guatemala",
    currencyName: "Quetzal",
    minorUnit: 2.0,
    currency_numeric_code: 320.0,
    rate: 4.347663437,
    alpha2: "GT",
  },
  GN: {
    alpha3: "GIN",
    currencyCode: "GNF",
    countryName: "Guinea",
    currencyName: "Guinea Franc",
    minorUnit: 0.0,
    currency_numeric_code: 324.0,
    rate: 3987.8799613415,
    alpha2: "GN",
  },
  GW: {
    alpha3: "GNB",
    currencyCode: "XOF",
    countryName: "Guinea-Bissau",
    currencyName: "CFA Franc BCEAO",
    minorUnit: 0.0,
    currency_numeric_code: 952.0,
    rate: 244.2429194024,
    alpha2: "GW",
  },
  GY: {
    alpha3: "GUY",
    currencyCode: "GYD",
    countryName: "Guyana",
    currencyName: "Guyana Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 328.0,
    rate: 131.1279359359,
    alpha2: "GY",
  },
  HT: {
    alpha3: "HTI",
    currencyCode: "USD",
    countryName: "Haiti",
    currencyName: "US Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 840.0,
    rate: 28.3296712613,
    alpha2: "HT",
  },
  HN: {
    alpha3: "HND",
    currencyCode: "HNL",
    countryName: "Honduras",
    currencyName: "Lempira",
    minorUnit: 2.0,
    currency_numeric_code: 340.0,
    rate: 11.7539858964,
    alpha2: "HN",
  },
  HK: {
    alpha3: "HKG",
    currencyCode: "HKD",
    countryName: "Hong Kong",
    currencyName: "Hong Kong Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 344.0,
    rate: 6.4506901255,
    alpha2: "HK",
  },
  HU: {
    alpha3: "HUN",
    currencyCode: "HUF",
    countryName: "Hungary",
    currencyName: "Forint",
    minorUnit: 2.0,
    currency_numeric_code: 348.0,
    rate: 149.39342,
    alpha2: "HU",
  },
  IS: {
    alpha3: "ISL",
    currencyCode: "ISK",
    countryName: "Iceland",
    currencyName: "Iceland Krona",
    minorUnit: 0.0,
    currency_numeric_code: 352.0,
    rate: 161.499914,
    alpha2: "IS",
  },
  IN: {
    alpha3: "IND",
    currencyCode: "INR",
    countryName: "India",
    currencyName: "Indian Rupee",
    minorUnit: 2.0,
    currency_numeric_code: 356.0,
    rate: 19.9780782714,
    alpha2: "IN",
  },
  ID: {
    alpha3: "IDN",
    currencyCode: "IDR",
    countryName: "Indonesia",
    currencyName: "Rupiah",
    minorUnit: 2.0,
    currency_numeric_code: 360.0,
    rate: 4985.697120233,
    alpha2: "ID",
  },
  IR: {
    alpha3: "IRN",
    currencyCode: "IRR",
    countryName: "Iran, Islamic Republic of",
    currencyName: "Iranian Rial",
    minorUnit: 2.0,
    currency_numeric_code: 364.0,
    rate: 12032.3262901592,
    alpha2: "IR",
  },
  IE: {
    alpha3: "IRL",
    currencyCode: "EUR",
    countryName: "Ireland",
    currencyName: "Euro",
    minorUnit: 2.0,
    currency_numeric_code: 978.0,
    rate: 0.995411,
    alpha2: "IE",
  },
  IL: {
    alpha3: "ISR",
    currencyCode: "ILS",
    countryName: "Israel",
    currencyName: "New Israeli Sheqel",
    minorUnit: 2.0,
    currency_numeric_code: 376.0,
    rate: 4.417778,
    alpha2: "IL",
  },
  IT: {
    alpha3: "ITA",
    currencyCode: "EUR",
    countryName: "Italy",
    currencyName: "Euro",
    minorUnit: 2.0,
    currency_numeric_code: 978.0,
    rate: 0.808406,
    alpha2: "IT",
  },
  JM: {
    alpha3: "JAM",
    currencyCode: "JMD",
    countryName: "Jamaica",
    currencyName: "Jamaican Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 388.0,
    rate: 79.7520811368,
    alpha2: "JM",
  },
  JP: {
    alpha3: "JPN",
    currencyCode: "JPY",
    countryName: "Japan",
    currencyName: "Yen",
    minorUnit: 0.0,
    currency_numeric_code: 392.0,
    rate: 107.146308,
    alpha2: "JP",
  },
  JO: {
    alpha3: "JOR",
    currencyCode: "JOD",
    countryName: "Jordan",
    currencyName: "Jordanian Dinar",
    minorUnit: 3.0,
    currency_numeric_code: 400.0,
    rate: 0.3318241844,
    alpha2: "JO",
  },
  KZ: {
    alpha3: "KAZ",
    currencyCode: "KZT",
    countryName: "Kazakhstan",
    currencyName: "Tenge",
    minorUnit: 2.0,
    currency_numeric_code: 398.0,
    rate: 113.6139740639,
    alpha2: "KZ",
  },
  KE: {
    alpha3: "KEN",
    currencyCode: "KES",
    countryName: "Kenya",
    currencyName: "Kenyan Shilling",
    minorUnit: 2.0,
    currency_numeric_code: 404.0,
    rate: 46.4925894803,
    alpha2: "KE",
  },
  KR: {
    alpha3: "KOR",
    currencyCode: "KRW",
    countryName: "Korea, Republic of",
    currencyName: "Won",
    minorUnit: 0.0,
    currency_numeric_code: 410.0,
    rate: 1003.749057,
    alpha2: "KR",
  },
  KW: {
    alpha3: "KWT",
    currencyCode: "KWD",
    countryName: "Kuwait",
    currencyName: "Kuwaiti Dinar",
    minorUnit: 3.0,
    currency_numeric_code: 414.0,
    rate: 0.1965774664,
    alpha2: "KW",
  },
  KG: {
    alpha3: "KGZ",
    currencyCode: "KGS",
    countryName: "Kyrgyzstan",
    currencyName: "Som",
    minorUnit: 2.0,
    currency_numeric_code: 417.0,
    rate: 20.6945371851,
    alpha2: "KG",
  },
  LA: {
    alpha3: "LAO",
    currencyCode: "LAK",
    countryName: "Lao People's Democratic Republic",
    currencyName: "Kip",
    minorUnit: 2.0,
    currency_numeric_code: 418.0,
    rate: 3243.1822021033,
    alpha2: "LA",
  },
  LV: {
    alpha3: "LVA",
    currencyCode: "EUR",
    countryName: "Latvia",
    currencyName: "Euro",
    minorUnit: 2.0,
    currency_numeric_code: 978.0,
    rate: 0.5725526009,
    alpha2: "LV",
  },
  LB: {
    alpha3: "LBN",
    currencyCode: "LBP",
    countryName: "Lebanon",
    currencyName: "Lebanese Pound",
    minorUnit: 2.0,
    currency_numeric_code: 422.0,
    rate: 905.3756590796,
    alpha2: "LB",
  },
  LS: {
    alpha3: "LSO",
    currencyCode: "ZAR",
    countryName: "Lesotho",
    currencyName: "Rand",
    minorUnit: 2.0,
    currency_numeric_code: 710.0,
    rate: 4.6720282497,
    alpha2: "LS",
  },
  LR: {
    alpha3: "LBR",
    currencyCode: "LRD",
    countryName: "Liberia",
    currencyName: "Liberian Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 430.0,
    rate: 0.7878178161,
    alpha2: "LR",
  },
  LT: {
    alpha3: "LTU",
    currencyCode: "EUR",
    countryName: "Lithuania",
    currencyName: "Euro",
    minorUnit: 2.0,
    currency_numeric_code: 978.0,
    rate: 0.5056933661,
    alpha2: "LT",
  },
  LU: {
    alpha3: "LUX",
    currencyCode: "EUR",
    countryName: "Luxembourg",
    currencyName: "Euro",
    minorUnit: 2.0,
    currency_numeric_code: 978.0,
    rate: 1.006819,
    alpha2: "LU",
  },
  MO: {
    alpha3: "MAC",
    currencyCode: "MOP",
    countryName: "Macao",
    currencyName: "Pataca",
    minorUnit: 2.0,
    currency_numeric_code: 446.0,
    rate: 6.5051700889,
    alpha2: "MO",
  },
  MK: {
    alpha3: "MKD",
    currencyCode: "MKD",
    countryName: "Macedonia, the Former Yugoslav Republic of",
    currencyName: "Denar",
    minorUnit: 2.0,
    currency_numeric_code: 807.0,
    rate: 22.9578790683,
    alpha2: "MK",
  },
  MG: {
    alpha3: "MDG",
    currencyCode: "MGA",
    countryName: "Madagascar",
    currencyName: "Malagasy Ariary",
    minorUnit: 2.0,
    currency_numeric_code: 969.0,
    rate: 898.1305322574,
    alpha2: "MG",
  },
  MW: {
    alpha3: "MWI",
    currencyCode: "MWK",
    countryName: "Malawi",
    currencyName: "Kwacha",
    minorUnit: 2.0,
    currency_numeric_code: 454.0,
    rate: 207.2345967366,
    alpha2: "MW",
  },
  MY: {
    alpha3: "MYS",
    currencyCode: "MYR",
    countryName: "Malaysia",
    currencyName: "Malaysian Ringgit",
    minorUnit: 2.0,
    currency_numeric_code: 458.0,
    rate: 1.659359408,
    alpha2: "MY",
  },
  MV: {
    alpha3: "MDV",
    currencyCode: "MVR",
    countryName: "Maldives",
    currencyName: "Rufiyaa",
    minorUnit: 2.0,
    currency_numeric_code: 462.0,
    rate: 11.9330554404,
    alpha2: "MV",
  },
  ML: {
    alpha3: "MLI",
    currencyCode: "XOF",
    countryName: "Mali",
    currencyName: "CFA Franc BCEAO",
    minorUnit: 0.0,
    currency_numeric_code: 952.0,
    rate: 218.9873362819,
    alpha2: "ML",
  },
  MT: {
    alpha3: "MLT",
    currencyCode: "EUR",
    countryName: "Malta",
    currencyName: "Euro",
    minorUnit: 2.0,
    currency_numeric_code: 978.0,
    rate: 0.6599106891,
    alpha2: "MT",
  },
  MR: {
    alpha3: "MRT",
    currencyCode: "MRO",
    countryName: "Mauritania",
    currencyName: "Ouguiya",
    minorUnit: 2.0,
    currency_numeric_code: 478.0,
    rate: 121.9741438658,
    alpha2: "MR",
  },
  MU: {
    alpha3: "MUS",
    currencyCode: "MUR",
    countryName: "Mauritius",
    currencyName: "Mauritius Rupee",
    minorUnit: 2.0,
    currency_numeric_code: 480.0,
    rate: 19.4631544921,
    alpha2: "MU",
  },
  MX: {
    alpha3: "MEX",
    currencyCode: "MXN",
    countryName: "Mexico",
    currencyName: "Mexican Peso",
    minorUnit: 2.0,
    currency_numeric_code: 484.0,
    rate: 10.113414,
    alpha2: "MX",
  },
  MD: {
    alpha3: "MDA",
    currencyCode: "MDL",
    countryName: "Moldova, Republic of",
    currencyName: "Moldovan Leu",
    minorUnit: 2.0,
    currency_numeric_code: 498.0,
    rate: 6.8596076671,
    alpha2: "MD",
  },
  MN: {
    alpha3: "MNG",
    currencyCode: "MNT",
    countryName: "Mongolia",
    currencyName: "Tugrik",
    minorUnit: 2.0,
    currency_numeric_code: 496.0,
    rate: 830.5842533262,
    alpha2: "MN",
  },
  ME: {
    alpha3: "MNE",
    currencyCode: "EUR",
    countryName: "Montenegro",
    currencyName: "Euro",
    minorUnit: 2.0,
    currency_numeric_code: 978.0,
    rate: 0.4330747878,
    alpha2: "ME",
  },
  MA: {
    alpha3: "MAR",
    currencyCode: "MAD",
    countryName: "Morocco",
    currencyName: "Moroccan Dirham",
    minorUnit: 2.0,
    currency_numeric_code: 504.0,
    rate: 4.2040235675,
    alpha2: "MA",
  },
  MZ: {
    alpha3: "MOZ",
    currencyCode: "MZN",
    countryName: "Mozambique",
    currencyName: "Mozambique Metical",
    minorUnit: 2.0,
    currency_numeric_code: 943.0,
    rate: 19.8153479252,
    alpha2: "MZ",
  },
  MM: {
    alpha3: "MMR",
    currencyCode: "MMK",
    countryName: "Myanmar",
    currencyName: "Kyat",
    minorUnit: 2.0,
    currency_numeric_code: 104.0,
    rate: 341.9029435274,
    alpha2: "MM",
  },
  NP: {
    alpha3: "NPL",
    currencyCode: "NPR",
    countryName: "Nepal",
    currencyName: "Nepalese Rupee",
    minorUnit: 2.0,
    currency_numeric_code: 524.0,
    rate: 36.6429864787,
    alpha2: "NP",
  },
  NL: {
    alpha3: "NLD",
    currencyCode: "EUR",
    countryName: "Netherlands",
    currencyName: "Euro",
    minorUnit: 2.0,
    currency_numeric_code: 978.0,
    rate: 0.893049,
    alpha2: "NL",
  },
  NZ: {
    alpha3: "NZL",
    currencyCode: "NZD",
    countryName: "New Zealand",
    currencyName: "New Zealand Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 554.0,
    rate: 1.639051,
    alpha2: "NZ",
  },
  NI: {
    alpha3: "NIC",
    currencyCode: "NIO",
    countryName: "Nicaragua",
    currencyName: "Cordoba Oro",
    minorUnit: 2.0,
    currency_numeric_code: 558.0,
    rate: 11.2550602059,
    alpha2: "NI",
  },
  NE: {
    alpha3: "NER",
    currencyCode: "XOF",
    countryName: "Niger",
    currencyName: "CFA Franc BCEAO",
    minorUnit: 0.0,
    currency_numeric_code: 952.0,
    rate: 220.8551165865,
    alpha2: "NE",
  },
  NG: {
    alpha3: "NGA",
    currencyCode: "NGN",
    countryName: "Nigeria",
    currencyName: "Naira",
    minorUnit: 2.0,
    currency_numeric_code: 566.0,
    rate: 123.6643454718,
    alpha2: "NG",
  },
  NO: {
    alpha3: "NOR",
    currencyCode: "NOK",
    countryName: "Norway",
    currencyName: "Norwegian Krone",
    minorUnit: 2.0,
    currency_numeric_code: 578.0,
    rate: 10.503934,
    alpha2: "NO",
  },
  OM: {
    alpha3: "OMN",
    currencyCode: "OMR",
    countryName: "Oman",
    currencyName: "Rial Omani",
    minorUnit: 3.0,
    currency_numeric_code: 512.0,
    rate: 0.1996185193,
    alpha2: "OM",
  },
  PK: {
    alpha3: "PAK",
    currencyCode: "PKR",
    countryName: "Pakistan",
    currencyName: "Pakistan Rupee",
    minorUnit: 2.0,
    currency_numeric_code: 586.0,
    rate: 32.0841329245,
    alpha2: "PK",
  },
  PA: {
    alpha3: "PAN",
    currencyCode: "USD",
    countryName: "Panama",
    currencyName: "US Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 840.0,
    rate: 0.5904469086,
    alpha2: "PA",
  },
  PG: {
    alpha3: "PNG",
    currencyCode: "PGK",
    countryName: "Papua New Guinea",
    currencyName: "Kina",
    minorUnit: 2.0,
    currency_numeric_code: 598.0,
    rate: 2.6156239748,
    alpha2: "PG",
  },
  PY: {
    alpha3: "PRY",
    currencyCode: "PYG",
    countryName: "Paraguay",
    currencyName: "Guarani",
    minorUnit: 0.0,
    currency_numeric_code: 600.0,
    rate: 2597.83056981,
    alpha2: "PY",
  },
  PE: {
    alpha3: "PER",
    currencyCode: "PEN",
    countryName: "Peru",
    currencyName: "Nuevo Sol",
    minorUnit: 2.0,
    currency_numeric_code: 604.0,
    rate: 1.735064019,
    alpha2: "PE",
  },
  PH: {
    alpha3: "PHL",
    currencyCode: "PHP",
    countryName: "Philippines",
    currencyName: "Philippine Peso",
    minorUnit: 2.0,
    currency_numeric_code: 608.0,
    rate: 20.1992831975,
    alpha2: "PH",
  },
  PL: {
    alpha3: "POL",
    currencyCode: "PLN",
    countryName: "Poland",
    currencyName: "Zloty",
    minorUnit: 2.0,
    currency_numeric_code: 985.0,
    rate: 1.882586,
    alpha2: "PL",
  },
  PT: {
    alpha3: "PRT",
    currencyCode: "EUR",
    countryName: "Portugal",
    currencyName: "Euro",
    minorUnit: 2.0,
    currency_numeric_code: 978.0,
    rate: 0.675777,
    alpha2: "PT",
  },
  QA: {
    alpha3: "QAT",
    currencyCode: "QAR",
    countryName: "Qatar",
    currencyName: "Qatari Rial",
    minorUnit: 2.0,
    currency_numeric_code: 634.0,
    rate: 2.8088335591,
    alpha2: "QA",
  },
  RO: {
    alpha3: "ROU",
    currencyCode: "RON",
    countryName: "Romania",
    currencyName: "New Romanian Leu",
    minorUnit: 2.0,
    currency_numeric_code: 946.0,
    rate: 1.8906062679,
    alpha2: "RO",
  },
  RU: {
    alpha3: "RUS",
    currencyCode: "RUB",
    countryName: "Russian Federation",
    currencyName: "Russian Ruble",
    minorUnit: 2.0,
    currency_numeric_code: 643.0,
    rate: 24.875185,
    alpha2: "RU",
  },
  RW: {
    alpha3: "RWA",
    currencyCode: "RWF",
    countryName: "Rwanda",
    currencyName: "Rwanda Franc",
    minorUnit: 0.0,
    currency_numeric_code: 646.0,
    rate: 282.7050348106,
    alpha2: "RW",
  },
  KN: {
    alpha3: "KNA",
    currencyCode: "XCD",
    countryName: "Saint Kitts and Nevis",
    currencyName: "East Caribbean Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 951.0,
    rate: 2.0633192695,
    alpha2: "KN",
  },
  LC: {
    alpha3: "LCA",
    currencyCode: "XCD",
    countryName: "Saint Lucia",
    currencyName: "East Caribbean Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 951.0,
    rate: 2.1050351275,
    alpha2: "LC",
  },
  VC: {
    alpha3: "VCT",
    currencyCode: "XCD",
    countryName: "Saint Vincent and the Grenadines",
    currencyName: "East Caribbean Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 951.0,
    rate: 1.9433453082,
    alpha2: "VC",
  },
  WS: {
    alpha3: "WSM",
    currencyCode: "WST",
    countryName: "Samoa",
    currencyName: "Tala",
    minorUnit: 2.0,
    currency_numeric_code: 882.0,
    rate: 1.8580851369,
    alpha2: "WS",
  },
  SM: {
    alpha3: "SMR",
    currencyCode: "EUR",
    countryName: "San Marino",
    currencyName: "Euro",
    minorUnit: 2.0,
    currency_numeric_code: 978.0,
    rate: 0.7711457759,
    alpha2: "SM",
  },
  ST: {
    alpha3: "STP",
    currencyCode: "STD",
    countryName: "Sao Tome and Principe",
    currencyName: "Dobra",
    minorUnit: 2.0,
    currency_numeric_code: 678.0,
    rate: 13568.2522931426,
    alpha2: "ST",
  },
  SA: {
    alpha3: "SAU",
    currencyCode: "SAR",
    countryName: "Saudi Arabia",
    currencyName: "Saudi Riyal",
    minorUnit: 2.0,
    currency_numeric_code: 682.0,
    rate: 1.9353407222,
    alpha2: "SA",
  },
  SN: {
    alpha3: "SEN",
    currencyCode: "XOF",
    countryName: "Senegal",
    currencyName: "CFA Franc BCEAO",
    minorUnit: 0.0,
    currency_numeric_code: 952.0,
    rate: 235.3119015777,
    alpha2: "SN",
  },
  RS: {
    alpha3: "SRB",
    currencyCode: "RSD",
    countryName: "Serbia",
    currencyName: "Serbian Dinar",
    minorUnit: 2.0,
    currency_numeric_code: 941.0,
    rate: 49.2224323128,
    alpha2: "RS",
  },
  SC: {
    alpha3: "SYC",
    currencyCode: "SCR",
    countryName: "Seychelles",
    currencyName: "Seychelles Rupee",
    minorUnit: 2.0,
    currency_numeric_code: 690.0,
    rate: 8.6343422044,
    alpha2: "SC",
  },
  SL: {
    alpha3: "SLE",
    currencyCode: "SLL",
    countryName: "Sierra Leone",
    currencyName: "Leone",
    minorUnit: 2.0,
    currency_numeric_code: 694.0,
    rate: 2306.145363991,
    alpha2: "SL",
  },
  SG: {
    alpha3: "SGP",
    currencyCode: "SGD",
    countryName: "Singapore",
    currencyName: "Singapore Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 702.0,
    rate: 1.1744391797,
    alpha2: "SG",
  },
  SK: {
    alpha3: "SVK",
    currencyCode: "EUR",
    countryName: "Slovakia",
    currencyName: "Euro",
    minorUnit: 2.0,
    currency_numeric_code: 978.0,
    rate: 0.547133,
    alpha2: "SK",
  },
  SI: {
    alpha3: "SVN",
    currencyCode: "EUR",
    countryName: "Slovenia",
    currencyName: "Euro",
    minorUnit: 2.0,
    currency_numeric_code: 978.0,
    rate: 0.674332,
    alpha2: "SI",
  },
  ZA: {
    alpha3: "ZAF",
    currencyCode: "ZAR",
    countryName: "South Africa",
    currencyName: "Rand",
    minorUnit: 2.0,
    currency_numeric_code: 710.0,
    rate: 6.2591178834,
    alpha2: "ZA",
  },
  SS: {
    alpha3: "SSD",
    currencyCode: "SSP",
    countryName: "South Sudan",
    currencyName: "South Sudanese Pound",
    minorUnit: 2.0,
    currency_numeric_code: 728.0,
    rate: 15.6364835201,
    alpha2: "SS",
  },
  ES: {
    alpha3: "ESP",
    currencyCode: "EUR",
    countryName: "Spain",
    currencyName: "Euro",
    minorUnit: 2.0,
    currency_numeric_code: 978.0,
    rate: 0.736368,
    alpha2: "ES",
  },
  LK: {
    alpha3: "LKA",
    currencyCode: "LKR",
    countryName: "Sri Lanka",
    currencyName: "Sri Lanka Rupee",
    minorUnit: 2.0,
    currency_numeric_code: 144.0,
    rate: 49.7030206455,
    alpha2: "LK",
  },
  SD: {
    alpha3: "SDN",
    currencyCode: "SDG",
    countryName: "Sudan",
    currencyName: "Sudanese Pound",
    minorUnit: 2.0,
    currency_numeric_code: 938.0,
    rate: 4.6853441445,
    alpha2: "SD",
  },
  SR: {
    alpha3: "SUR",
    currencyCode: "SRD",
    countryName: "Suriname",
    currencyName: "Surinam Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 968.0,
    rate: 3.6732792089,
    alpha2: "SR",
  },
  SZ: {
    alpha3: "SWZ",
    currencyCode: "SZL",
    countryName: "Swaziland",
    currencyName: "Lilangeni",
    minorUnit: 2.0,
    currency_numeric_code: 748.0,
    rate: 5.2233282109,
    alpha2: "SZ",
  },
  SE: {
    alpha3: "SWE",
    currencyCode: "SEK",
    countryName: "Sweden",
    currencyName: "Swedish Krona",
    minorUnit: 2.0,
    currency_numeric_code: 752.0,
    rate: 9.583163,
    alpha2: "SE",
  },
  CH: {
    alpha3: "CHE",
    currencyCode: "CHF",
    countryName: "Switzerland",
    currencyName: "Swiss Franc",
    minorUnit: 2.0,
    currency_numeric_code: 756.0,
    rate: 1.413706,
    alpha2: "CH",
  },
  TJ: {
    alpha3: "TJK",
    currencyCode: "TJS",
    countryName: "Tajikistan",
    currencyName: "Somoni",
    minorUnit: 2.0,
    currency_numeric_code: 972.0,
    rate: 2.3315824374,
    alpha2: "TJ",
  },
  TZ: {
    alpha3: "TZA",
    currencyCode: "TZS",
    countryName: "Tanzania, United Republic of",
    currencyName: "Tanzanian Shilling",
    minorUnit: 2.0,
    currency_numeric_code: 834.0,
    rate: 809.2830071798,
    alpha2: "TZ",
  },
  TH: {
    alpha3: "THA",
    currencyCode: "THB",
    countryName: "Thailand",
    currencyName: "Baht",
    minorUnit: 2.0,
    currency_numeric_code: 764.0,
    rate: 12.8206274699,
    alpha2: "TH",
  },
  TL: {
    alpha3: "TLS",
    currencyCode: "USD",
    countryName: "Timor-Leste",
    currencyName: "US Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 840.0,
    rate: 0.6527956292,
    alpha2: "TL",
  },
  TG: {
    alpha3: "TGO",
    currencyCode: "XOF",
    countryName: "Togo",
    currencyName: "CFA Franc BCEAO",
    minorUnit: 0.0,
    currency_numeric_code: 952.0,
    rate: 233.7891450672,
    alpha2: "TG",
  },
  TO: {
    alpha3: "TON",
    currencyCode: "TOP",
    countryName: "Tonga",
    currencyName: "Pa\u2019anga",
    minorUnit: 2.0,
    currency_numeric_code: 776.0,
    rate: 1.6288708451,
    alpha2: "TO",
  },
  TT: {
    alpha3: "TTO",
    currencyCode: "TTD",
    countryName: "Trinidad and Tobago",
    currencyName: "Trinidad and Tobago Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 780.0,
    rate: 5.6727887069,
    alpha2: "TT",
  },
  TN: {
    alpha3: "TUN",
    currencyCode: "TND",
    countryName: "Tunisia",
    currencyName: "Tunisian Dinar",
    minorUnit: 3.0,
    currency_numeric_code: 788.0,
    rate: 0.8286624871,
    alpha2: "TN",
  },
  TR: {
    alpha3: "TUR",
    currencyCode: "TRY",
    countryName: "Turkey",
    currencyName: "Turkish Lira",
    minorUnit: 2.0,
    currency_numeric_code: 949.0,
    rate: 1.604035,
    alpha2: "TR",
  },
  UG: {
    alpha3: "UGA",
    currencyCode: "UGX",
    countryName: "Uganda",
    currencyName: "Uganda Shilling",
    minorUnit: 0.0,
    currency_numeric_code: 800.0,
    rate: 1202.1268342371,
    alpha2: "UG",
  },
  UA: {
    alpha3: "UKR",
    currencyCode: "UAH",
    countryName: "Ukraine",
    currencyName: "Hryvnia",
    minorUnit: 2.0,
    currency_numeric_code: 980.0,
    rate: 5.9138410499,
    alpha2: "UA",
  },
  AE: {
    alpha3: "ARE",
    currencyCode: "AED",
    countryName: "United Arab Emirates",
    currencyName: "UAE Dirham",
    minorUnit: 2.0,
    currency_numeric_code: 784.0,
    rate: 2.8061446966,
    alpha2: "AE",
  },
  GB: {
    alpha3: "GBR",
    currencyCode: "GBP",
    countryName: "United Kingdom",
    currencyName: "Pound Sterling",
    minorUnit: 2.0,
    currency_numeric_code: 826.0,
    rate: 0.802082,
    alpha2: "GB",
  },
  US: {
    alpha3: "USA",
    currencyCode: "USD",
    countryName: "United States",
    currencyName: "US Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 840.0,
    rate: 1.0,
    alpha2: "US",
  },
  UY: {
    alpha3: "URY",
    currencyCode: "UYU",
    countryName: "Uruguay",
    currencyName: "Peso Uruguayo",
    minorUnit: 2.0,
    currency_numeric_code: 858.0,
    rate: 23.4348384801,
    alpha2: "UY",
  },
  VU: {
    alpha3: "VUT",
    currencyCode: "VUV",
    countryName: "Vanuatu",
    currencyName: "Vatu",
    minorUnit: 0.0,
    currency_numeric_code: 548.0,
    rate: 116.283781114,
    alpha2: "VU",
  },
  VE: {
    alpha3: "VEN",
    currencyCode: "VEF",
    countryName: "Venezuela, Bolivarian Republic of",
    currencyName: "Bolivar",
    minorUnit: 2.0,
    currency_numeric_code: 937.0,
    rate: 59.3735247852,
    alpha2: "VE",
  },
  VN: {
    alpha3: "VNM",
    currencyCode: "VND",
    countryName: "Viet Nam",
    currencyName: "Dong",
    minorUnit: 0.0,
    currency_numeric_code: 704.0,
    rate: 9008.6904259423,
    alpha2: "VN",
  },
  ZM: {
    alpha3: "ZMB",
    currencyCode: "ZMW",
    countryName: "Zambia",
    currencyName: "Zambian Kwacha",
    minorUnit: 2.0,
    currency_numeric_code: 967.0,
    rate: 3.7457475534,
    alpha2: "ZM",
  },
  ZW: {
    alpha3: "ZWE",
    currencyCode: "ZWL",
    countryName: "Zimbabwe",
    currencyName: "Zimbabwe Dollar",
    minorUnit: 2.0,
    currency_numeric_code: 932.0,
    rate: 0.5086361303,
    alpha2: "ZW",
  },
};

function getPrice(usdPrice, alpha2, throwError = false) {
  if (alpha2 in rates) {
    return Math.round(usdPrice * rates[alpha2].rate);
  } else {
    if (throwError) {
      throw `Insufficient data for this country code: ${alpha2}\n`;
    } else {
      return usdPrice;
    }
  }
}

function getRate(alpha2, throwError = false) {
  if (alpha2 in rates) {
    return rates[alpha2].rate;
  } else {
    if (throwError) {
      throw `Insufficient data for this country code: ${alpha2}\n`;
    } else {
      return 1;
    }
  }
}

function getInfo(alpha2, throwError = false) {
  if (alpha2 in rates) {
    return rates[alpha2];
  } else {
    if (throwError) {
      throw `Insufficient data for this country code: ${alpha2}\n`;
    } else {
      return undefined;
    }
  }
}

function getCountryName(alpha2, throwError = false) {
  if (alpha2 in rates) {
    return rates[alpha2].countryName;
  } else {
    if (throwError) {
      throw `Insufficient data for this country code: ${alpha2}\n`;
    } else {
      return undefined;
    }
  }
}


function getCurrencyName(alpha2, throwError = false) {
  if (alpha2 in rates) {
    return rates[alpha2].currencyName;
  } else {
    if (throwError) {
      throw `Insufficient data for this country code: ${alpha2}\n`;
    } else {
      return undefined;
    }
  }
}

module.exports.getPrice = getPrice;
module.exports.getRate = getRate;
module.exports.getInfo = getInfo;
module.exports.getCountryName = getCountryName;
module.exports.getCurrencyName = getCurrencyName;
module.exports.rates = rates;
